---
baseURL: https://kbrahul.netlify.com
languageCode: en-us
title: K B Rahul 
theme: PaperMod
googleAnalytics: None
languages:
  en:
    languageName: English
    weight: "1"
    menu:
      main:
      - name: Archive
        url: archives
        weight: "5"
      - name: Search
        url: search/
        weight: "10"
      - name: Tags
        url: tags/
        weight: "10"
      - name: Categories
        url: categories/
        weight: "10"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  ShowReadingTime: true
  env: production
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  author: K B Rahul
  images: https://res.cloudinary.com/kbrassetplus/image/upload/v1613825538/sample.jpg
  profileMode:
    enabled: true
    title: "Pictures, Stories, Code and more" # optional default will be site title
    subtitle: "Happiness is a habit"
    imageUrl: "https://res.cloudinary.com/kbrassetplus/image/upload/v1613825538/sample.jpg" # optional
    imageTitle: "Some Image Title" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
        - name: Archive
          url: "/archives"
        - name: Github
          url: "https://github.com/kb-rahul"
        - name: Twitter
          url: "https://twitter.com/kbrahul_"
  editPost:
    URL: https://github.com/kb-rahul/the-imperfect-yogi/tree/main/content
    Text: Suggest Changes
    appendFilePath: true
  socialIcons:
  - name: KoFi
    url: https://ko-fi.com/theimperfectyogi
  - name: youtube
    url: https://youtube.com
  - name: instagram
    url: https://www.instagram.com/the_imperfect_yogi_/
  - name: twitter
    url: https://twitter.com/kbrahul_
  - name: email
    url: mailto:kb.rahul15@gmail.com?subject=(Link the article here)
